# Model Information
# GFLOPs  GMACs   Params.(M)
#  15.24   7.53    7.125
# Throughput (ins./s): 115.24562648667185

model:
  NAME: BaseSeg
  encoder_args:
    NAME: PointNextRepEncoder
    blocks: [1, 3, 5, 3, 3]
    strides: [1, 4, 4, 4, 4]
    sa_layers: 1 
    sa_use_res: False 
    width: 32
    in_channels: 4
    expansion: 4
    radius: 0.1
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'ballquery'
      normalize_dp: True
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  decoder_args:
    NAME: All4ConcatDecoder256_64_DynGCN
  longrange_args:
    NAME: DynGCN
    blocks: [4] #[2]
    strides: [1]
    sa_layers: 1 
    sa_use_res: False 
    width: 64
    in_channels: 4
    expansion: 4
    # radius: 0.1
    nsample: 32
    aggr_args:
      feature_type: 'dp_fj'
      reduction: 'max'
    group_args:
      NAME: 'dynamic_knn'
      dilation: 4 #4 #1
      normalize_dp: False
      relative_xyz: False
    conv_args:
      order: conv-norm-act
    act_args:
      act: 'relu'
    norm_args:
      norm: 'bn'
  cls_args:
    NAME: SegHead
    num_classes: 13
    in_channels: null
    norm_args:
      norm: 'bn'

batch_size: 8 #8
seed: 2425 #4333 #2425